system:
  env: dev
  name: "log"
  port: 8898


database:
  mysqlDataBase:
    host: 203.195.210.218
    port: 3306
    username: "wjy_blog"
    password: "M3MMTYcTCcc75iwA"
    db: "wjy_blog"
    charset: utf8mb4 # 编码格式
    max_idle_connections: 10 # 空闲连接池中连接的最大数量
    max_open_connections: 100 # 打开数据库连接的最大数量
    log_mode: info # 日志级别
    enable_file_log_writer: true # 是否启用日志文件
    log_filename: sql.log # 日志文件名称
  redisDataBase:
    host: 150.158.125.224
    port: 6379
    username: ""
    password: "AS_999999999Ai"
    db: 11
    max_idle: 30          # 最大空闲连接数
    max_active: 30        # 最大活跃连接数
    idle_timeout: 200     # 空闲连接最大闲置等待时间，超过指定时间后关闭连接，释放资源

logger:
  level: "debug"
  logger_path: "./logs"
  success_path: "./logs/success.log"
  error_path: "./logs/error.log"
  max_size: 200
  max_backups: 10
  max_age: 30
